export type MarketingAsset = {
  id: string;
  label: string;
  group: "fonds" | "gold" | "real-estate" | "insurance" | "energy" | "partners" | "contact";
  kind: "component" | "image" | "bitmap-required";
  component?: string;
  path?: string;
  notes?: string;
};

export const marketingAssetCatalog: MarketingAsset[] = [
  {
    id: "fonds-icon-growth",
    label: "Icon bieu do tang truong",
    group: "fonds",
    kind: "component",
    component: "GrowthChartIcon",
  },
  {
    id: "fonds-icon-piggy-bank",
    label: "Icon heo tiet kiem",
    group: "fonds",
    kind: "component",
    component: "PiggyBankIcon",
  },
  {
    id: "fonds-icon-flexible-choice",
    label: "Icon linh hoat cao",
    group: "fonds",
    kind: "component",
    component: "FlexibleChoiceIcon",
  },
  {
    id: "fonds-logo-dws",
    label: "Logo DWS",
    group: "fonds",
    kind: "component",
    component: "DwsLogoMark",
  },
  {
    id: "fonds-logo-allianz",
    label: "Logo Allianz Global Investors",
    group: "fonds",
    kind: "component",
    component: "AllianzLogoMark",
  },
  {
    id: "fonds-hero-euro",
    label: "Anh ECB euro tren trang Fonds Sparplan",
    group: "fonds",
    kind: "image",
    path: "/images/gallery-05.jpeg",
  },
  {
    id: "fonds-cost-average-flow",
    label: "So do Cost-Average thang vao Fonds",
    group: "fonds",
    kind: "image",
    path: "/images/fonds-monthly-to-fonds.jpeg",
  },
  {
    id: "fonds-cost-average-shares",
    label: "So do nhieu/it co phan theo gia thi truong",
    group: "fonds",
    kind: "image",
    path: "/images/fonds-cost-average.jpeg",
  },
  {
    id: "fonds-cost-average-chart",
    label: "Bieu do so luong co phan mua hang thang",
    group: "fonds",
    kind: "image",
    path: "/images/fonds-monthly-shares-chart.jpeg",
  },
  {
    id: "gold-icon-umbrella",
    label: "Icon du bao ve",
    group: "gold",
    kind: "component",
    component: "UmbrellaIcon",
  },
  {
    id: "gold-icon-direction",
    label: "Icon bien chi huong",
    group: "gold",
    kind: "component",
    component: "DirectionSignIcon",
  },
  {
    id: "gold-icon-hand-euro",
    label: "Icon ban tay va dong Euro",
    group: "gold",
    kind: "component",
    component: "HandEuroIcon",
  },
  {
    id: "gold-bar-details",
    label: "Anh chi tiet thoi vang Geiger Edelmetalle",
    group: "gold",
    kind: "bitmap-required",
    notes: "Anh da gui trong chat; can file goc de luu vao public/images.",
  },
  {
    id: "real-estate-logo-badenia",
    label: "Logo Deutsche Bausparkasse Badenia",
    group: "real-estate",
    kind: "component",
    component: "BadeniaLogoMark",
  },
  {
    id: "real-estate-icon-certificate",
    label: "Icon chung nhan",
    group: "real-estate",
    kind: "component",
    component: "DocumentCheckIcon",
  },
  {
    id: "real-estate-icon-hands-cycle",
    label: "Icon doi tay va vong lap",
    group: "real-estate",
    kind: "component",
    component: "CycleIcon",
  },
  {
    id: "real-estate-icon-house",
    label: "Icon nha",
    group: "real-estate",
    kind: "component",
    component: "HouseLineIcon",
  },
  {
    id: "real-estate-immostart-diagram",
    label: "So do ImmoStart Badenia",
    group: "real-estate",
    kind: "image",
    path: "/images/bauspar-immostart-diagram.jpeg",
  },
  {
    id: "real-estate-rate-risk-chart",
    label: "Bieu do lai suat va tong chi phi",
    group: "real-estate",
    kind: "image",
    path: "/images/credit-consolidation-diagram.jpeg",
  },
  {
    id: "real-estate-fingerhaus-awards",
    label: "Logo va giai thuong FingerHaus",
    group: "real-estate",
    kind: "bitmap-required",
    notes: "Can file anh goc neu muon dung chinh xac.",
  },
  {
    id: "partners-logo-generali",
    label: "Logo Generali",
    group: "partners",
    kind: "component",
    component: "GeneraliLogoMark",
  },
  {
    id: "partners-logo-fingerhaus",
    label: "Logo FingerHaus",
    group: "partners",
    kind: "component",
    component: "FingerHausLogoMark",
  },
  {
    id: "partners-tablet",
    label: "Anh doi tac tren may tinh bang",
    group: "partners",
    kind: "image",
    path: "/images/partners-tablet.jpeg",
  },
  {
    id: "insurance-icon-lock",
    label: "Icon o khoa",
    group: "insurance",
    kind: "component",
    component: "LockIcon",
  },
  {
    id: "insurance-icon-profile",
    label: "Icon ho so ca nhan",
    group: "insurance",
    kind: "component",
    component: "ProfileCircleIcon",
  },
  {
    id: "insurance-icon-stopwatch",
    label: "Icon dong ho bam gio",
    group: "insurance",
    kind: "component",
    component: "StopwatchIcon",
  },
  {
    id: "insurance-icon-broken-plate",
    label: "Icon vat dung bi vo",
    group: "insurance",
    kind: "component",
    component: "BrokenPlateIcon",
  },
  {
    id: "insurance-icon-sofa",
    label: "Icon ghe sofa",
    group: "insurance",
    kind: "component",
    component: "SofaIcon",
  },
  {
    id: "insurance-icon-health-cross",
    label: "Icon dau cong y te",
    group: "insurance",
    kind: "component",
    component: "HealthCrossIcon",
  },
  {
    id: "insurance-advocard",
    label: "Anh ADVOCARD 360 Privat",
    group: "insurance",
    kind: "image",
    path: "/images/advocard-360-private.jpeg",
  },
  {
    id: "energy-icon-house-cycle",
    label: "Icon nha va vong lap",
    group: "energy",
    kind: "component",
    component: "HouseCycleIcon",
  },
  {
    id: "energy-icon-solar-panel",
    label: "Icon tam pin nang luong mat troi",
    group: "energy",
    kind: "component",
    component: "SolarPanelIcon",
  },
  {
    id: "energy-vde-certificate",
    label: "Anh chung nhan VDE va giai thuong",
    group: "energy",
    kind: "bitmap-required",
    notes: "Can file anh goc de luu dung noi dung.",
  },
  {
    id: "contact-qr-vuthebao",
    label: "QR online Vu The Bao",
    group: "contact",
    kind: "image",
    path: "/images/qr-vuthebao.png",
  },
];
